export enum ErrorCode {
  INVALID_USERNAME_PASSWORD = 1002,

  PASSWORD_CHANGED = 1102,
  ACCESS_TOKEN_EXPIRED = 1105,
  REFRESH_TOKEN_EXPIRED = 1107,

  VOUCHER_NOT_FOUND = 1201,
  VOUCHER_EXPIRED = 1202,
}

export const StorageKey = {
  FCM_TOKEN: 'fcm_token',
};
